version: 2
jobs:
  build:
    docker:
      # See https://circleci.com/docs/2.0/circleci-images/ ...
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/repo
    steps:
          - checkout
          - run:
              name: Clean & install
              command: ./gradlew clean build -x test
          - run:
              name: Unit tests
              command: ./gradlew test
          - run:
              name: Collect test results
              command: |
                mkdir -p test-results/junit
                cp -pR scenarioo-server/build/test-results/test test-results/server
                cp -pR scenarioo-client/TESTS* test-results/javascript
                cp -pR scenarioo-docu-generation-example/build/test-results/test test-results/docu
          - store_test_results:
              path: test-results
#          - store_artifacts:
#              path: scenarioo-server/build/libs/scenarioo-latest.war
