version: 2
jobs:
  build:
    docker:
      # See https://circleci.com/docs/2.0/circleci-images/ ...
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/repo
    steps:
          - checkout
          - run:
              name: Clean & install
              command: ./gradlew clean build -x test
          - run:
              name: Unit tests
              command: ./gradlew test -x scenarioo-client:npm_test
          - run:
              name: JS tests
              command: ./gradlew scenarioo-client:npm_test
              when: always
          - run:
              name: Collect test results
              command: |
                mkdir -p test-results/javascript
                ls -l scenarioo-server/build/test-results/test || true
                cp -pR scenarioo-server/build/test-results/test test-results/server || true
                ls -l scenarioo-client/ || true
                cp -pR scenarioo-client/TESTS* test-results/javascript || true
                ls -l scenarioo-docu-generation-example/build/test-results/test || true
                cp -pR scenarioo-docu-generation-example/build/test-results/test test-results/docu || true
                ls -l test-results/* || true
              when: always
          - store_test_results:
              path: test-results
          -store_artifacts:
              path: test-results
#          - store_artifacts:
#              path: scenarioo-server/build/libs/scenarioo-latest.war
