version: 2
jobs:
  build:
    docker:
      # See https://circleci.com/docs/2.0/circleci-images/ ...
      - image: circleci/openjdk:8-jdk-browsers
      - image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
        environment:
          cluster.name: elasticsearch
          xpack.ml.enabled: false
          xpack.security.enabled: false
          ES_JAVA_OPTS: -Xms512m -Xmx512m
    working_directory: ~/repo
    steps:
          - checkout
          - run:
              name: Clean & install
              command: ./gradlew clean build -x test
          - run:
              name: Unit tests
              command: ./gradlew test -x scenarioo-client:npm_test --continue
          - run:
              name: JS tests
              command: ./gradlew scenarioo-client:npm_test
              when: always
          - run:
              name: E2E tests
              command: |
                SCENARIOO_DATA=./scenarioo-docu-generation-example/build/scenarioDocuExample java -Xms512m -Xmx512m -jar scenarioo-server/build/libs/scenarioo-latest.war > scenarioo-server.log &
                echo "After start"
                export PROTRACTOR_BASE_URL=http://localhost:8080/scenarioo
                export BRANCH="$CIRCLE_BRANCH"
                echo "Before sleep"
                sleep 1m || true
                echo "After sleep"
                curl -I $PROTRACTOR_BASE_URL || true
                curl $PROTRACTOR_BASE_URL || true
                curl -o page.html $PROTRACTOR_BASE_URL || true
                pkill java
              when: always
          - store_artifacts:
              path: scenarioo-server.log
          - store_artifacts:
              path: scenarioo-client/scenariooDocumentation
          - store_artifacts:
              path: page.html
          - run:
              name: Collect test results
              command: |
                mkdir -p test-results/javascript
                cp -pR scenarioo-client/TESTS* test-results/javascript || true
                cp -pR scenarioo-client/test-reports test-results/e2e || true
                cp -pR scenarioo-server/build/test-results/test test-results/server || true
                cp -pR scenarioo-validator/build/test-results/test test-results/validator || true
                cp -pR scenarioo-docu-generation-example/build/test-results/test test-results/docu || true
              when: always
          - store_test_results:
              path: test-results
          - store_artifacts:
              path: test-results
# Enable once we are ready to deploy it automatically on our server
#          - store_artifacts:
#              path: scenarioo-server/build/libs/scenarioo-latest.war
